Add windows and mac binaries to the release

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -70,6 +70,7 @@ jobs:
       - run: yarn validate-changelog
       - name: Ensure a clean working directory
         run: git diff --name-status --exit-code
+
   build:
     name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
     runs-on: ${{ matrix.os }}
@@ -159,3 +160,52 @@ jobs:
             dist/GitHubDesktopSetup-${{matrix.arch}}.msi
             dist/bundle-size.json
           if-no-files-found: error
+
+  publish:
+    name: Publish artifacts
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Set release tag
+        run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
+
+      - name: Download all artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: './artifacts'
+
+      - name: Display structure of downloaded files
+        run: ls -R
+        working-directory: './artifacts'
+
+      - name: Wait for release to be available
+        run: |
+          echo "Waiting for release $RELEASE_TAG to be available..."
+          for i in {1..180}; do
+            response=$(curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/$RELEASE_TAG")
+            if echo "$response" | grep -q '"id":'; then
+              echo "Release found."
+              exit 0
+            fi
+            echo "Release not found. Retrying in 10 seconds..."
+            sleep 10
+          done
+          echo "Release $RELEASE_TAG not found after 30 minutes."
+          exit 1
+
+      - name: Rename artifacts
+        run: |
+          # GitHubDesktopSetup-<arch>.<ext> -> GitHubDesktopPlus-<release_tag>-windows-<arch>.<ext>
+          for file in $(find ./artifacts -type f -name "GitHubDesktopSetup-*"); do
+            mv --verbose $file $(echo $file | sed -E "s/GitHubDesktopSetup-(.*)\\.(.*)/GitHubDesktopPlus-${{ env.RELEASE_TAG }}-windows-\\1.\\2/")
+          done
+
+          # GitHub Desktop-<arch>.zip -> GitHubDesktopPlus-<release_tag>-macOS-<arch>.zip
+          for file in $(find ./artifacts -type f -name "GitHub Desktop-*.zip"); do
+            mv --verbose $file $(echo $file | sed -E "s/GitHub Desktop-(.*)\\.zip/GitHubDesktopPlus-${{ env.RELEASE_TAG }}-macOS-\\1.zip/")
+          done
+
+      - name: Upload assets to release
+        run: gh release upload $RELEASE_TAG ./artifacts/* --clobber
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
